name: sfc_cae
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8.5
  - pip
  - wheel
  - ipython
  - jupyter
  - matplotlib
  - numpy
  - pandas
  - scipy
  - pytest
  - pip:
    - vtk
    - progressbar
    - livelossplot
    - meshio[all]
    - cmocean
    - dash
    - torch
    - timm
    - atari-py==0.2.6
    - gym==0.15.4
    - opencv-python==4.1.2.30
    - psutil==5.6.7
    - pyglet==1.3.2
    - tensorflow-addons==0.6.0
    - tensorflow-data-validation==0.15.0
    - tensorflow-metadata==0.15.1
    - tensorflow-model-analysis==0.15.4
    - tensorflow-serving-api==2.0.0 # or tensorflow-serving-api-gpu if gpu
    - tensorflow-transform==0.15.0
    - tf-agents==0.3.0rc0
    - tfx==0.15.0
    - urlextract==0.13.0

