name: sfc-cae
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8.5
  - pip
  - wheel
  - ipython=7.10.1
  - jupyter=1.0.0
  - matplotlib=3.1.2
  - numpy=1.17.3
  - pandas=0.25.3
  - scipy
  - pytest=5.1.1
  - pip:
    - vtk
    - progressbar
    - livelossplot
    - meshio[all]
    - cmocean
    - dash
    - torch

