name: sfc_cae
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8.5
  - pip
  - wheel
  - ipython
  - jupyter
  - matplotlib
  - numpy
  - pandas
  - scipy
  - pytest
  - pip:
    - vtk
    - progressbar
    - livelossplot
    - meshio[all]
    - cmocean
    - dash
    - torch

