name: sfc_cae
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8.5
  - pip=21.1.3
  - wheel
  - ipython
  - jupyter
  - matplotlib
  - numpy
  - pandas
  - scipy
  - pytest
  - pip:
    - vtk==9.1.0
    - progressbar==3.38.0
    - livelossplot==0.5.4
    - meshio == 5.0.2
    - cmocean==2.0
    - dash
    - torch==1.10.0+cu111
    - timm==0.4.12
    - gdown==3.6.4
    # - atari-py==0.2.6
    # - gym==0.15.4
    # - opencv-python==4.1.2.30
    # - psutil==5.6.7
    # - pyglet==1.3.2
    # - tensorflow~=2.6.0
    # - tf-agents~=0.3.0
    # - tfx>=0.15.0
    # - urlextract~=0.13.0

