name: run-pytest-tests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# This job installs dependencies and runs tests
jobs:

  pytest-unbuntu:
    
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          environment-file: environment.yml
          auto-activate-base: true
          # activate-environment: sfc_cae
      
      # activate environment 
      - name: Activate SFC-CAE
        run: source activate sfc_cae
          
      # get vtktools
      - name: Download vtktools
        run: wget https://raw.githubusercontent.com/FluidityProject/fluidity/main/python/vtktools.py

      # compile fortran
      - name: Compile Fortran library
        run: python -m numpy.f2py -c space_filling_decomp_new.f90 -m space_filling_decomp_new

      # run pytests      
      - name: Test with pytest
        run: python -m pytest tests/ --doctest-modules -v

  pytest-windows:
    
    runs-on: windows-latest
    steps:

      - uses: actions/checkout@v2

      # only linux supports Container action
      - uses: conda-incubator/setup-miniconda@v2
        with:
          environment-file: environment.yml
          auto-activate-base: true
          activate-environment: sfc_cae
      
      # get vtktools
      - name: Download vtktools
        run: C:\msys64\usr\bin\wget.exe https://raw.githubusercontent.com/FluidityProject/fluidity/main/python/vtktools.py

      # compile fortran
      - name: Compile Fortran library
        run: f2py -c space_filling_decomp_new.f90 -m space_filling_decomp_new --compiler=mingw32

      # run pytests      
      - name: Test with pytest
        run: python -m pytest tests/ --doctest-modules -v