name: run-pytest-tests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# This job installs dependencies and runs pytests for three kinds of operating systems
jobs:

  pytest-unbuntu:
    
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # setup python
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8.5'

      # pip install the module
      - name: Pip install
        run: pip install -e .

      # run pytests      
      - name: Test with pytest
        run: python -m pytest tests/ --doctest-modules -v

  pytest-macOS:

    runs-on: macos-latest
                      
    steps:
      - uses: actions/checkout@v2

      # setup python
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8.5'
      
      # pip install the module
      - name: Pip install
        run: pip3 install -e .

      # run pytests      
      - name: Test with pytest
        run: python3 -m pytest tests/ --doctest-modules -v      

  pytest-windows:
    
    runs-on: windows-latest
    steps:

      - uses: actions/checkout@v2
      
      # configure conda environment
      - uses: conda-incubator/setup-miniconda@v2
        with:
          environment-file: environment.yml
          auto-activate-base: true
          activate-environment: sfc_cae
      
      # compile fortran code with MinGW
      - name: Compile Fortran Library
        run: f2py -c space_filling_decomp_new.f90 -m space_filling_decomp_new --compiler=mingw32

      # run pytests      
      - name: Test with pytest
        run: python -m pytest tests/ --doctest-modules -v