name: run-pytest-tests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# This job installs dependencies and runs pytests for both ubuntu and windows.
jobs:

  pytest-ubuntu:
    
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # setup python
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8.5'

      # pip install the module
      - name: Pip install
        run: pip install -e .

      # download dataset and trained-model
      - name: Download FPC CG Dataset
        run: sh get_FPC_data_CG.sh

      # run pytests      
      - name: Test with pytest
        run: python -m pytest tests/tests.py --doctest-modules -v 

  pytest-windows:
    
    runs-on: windows-latest
    steps:

      - uses: actions/checkout@v2
      
      # configure conda environment
      - uses: conda-incubator/setup-miniconda@v2
        with:
          environment-file: environment.yml
          auto-activate-base: true
          activate-environment: sfc_cae
      
      # compile fortran code with MinGW
      - name: Compile Fortran Library
        run: |
             f2py -c space_filling_decomp_new.f90 -m space_filling_decomp_new --compiler=mingw32
             f2py -c x_conv_fixed_length.f90 -m sfc_interpolate --compiler=mingw32

      # download CG dataset for testing
      - name: Download FPC CG Dataset
        run: |
          C:\msys64\usr\bin\wget.exe --load-cookies /tmp/cookies.txt "https://drive.google.com/uc?export=download&confirm=$(C:\msys64\usr\bin\wget.exe --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://drive.google.com/uc?export=download&id=1BpItXH0Rvwf2NvTBLTIZwr7-LmSyLd9M' -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).* \
          /\1\n/p')&id=1BpItXH0Rvwf2NvTBLTIZwr7-LmSyLd9M" -O FPC_Re3900_CG_new.zip && rm -rf /tmp/cookies.txt
          7z x FPC_Re3900_CG_new.zip
          C:\msys64\usr\bin\wget.exe --no-check-certificate 'https://drive.google.com/uc?export=download&id=1SmMWemkN2ykR3Hwa_IoU2ka49P69_G5j' -O 'Variational_False_Changelr_False_Latent_16_Nearest_neighbouring_False_SFC_nums_2_startlr_0.0001_n_epoches_2000_dict.pth'
          C:\msys64\usr\bin\wget.exe --no-check-certificate 'https://drive.google.com/uc?export=download&id=1Ki3i5wLsdVgx3YupQlLQIZf1A34y5RgN' -O 'Variational_True_Changelr_False_Latent_16_Nearest_neighbouring_False_SFC_nums_2_startlr_0.0001_n_epoches_2000_dict.pth'

      # run pytests      
      - name: Test with pytest
        run: python -m pytest tests/tests.py --doctest-modules -v
